mode: mock
systemd_units:
  AMF: open5gs-amfd.service
  SMF: open5gs-smfd.service
  UPF: open5gs-upfd.service
  NRF: open5gs-nrfd.service
  UDM: open5gs-udmd.service
  AUSF: open5gs-ausfd.service
mock_status:
  AMF: UP
  SMF: UP
  UPF: UP
  NRF: UP
  UDM: UP
  AUSF: UP
